// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class InvalidTheme {
    "path": string;
    "id": string;
    "reason": string;

    /** Creates a new InvalidTheme instance. */
    constructor($$source: Partial<InvalidTheme> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InvalidTheme instance from a string or object.
     */
    static createFrom($$source: any = {}): InvalidTheme {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InvalidTheme($$parsedSource as Partial<InvalidTheme>);
    }
}

export class Palette {
    "black": string;
    "red": string;
    "green": string;
    "yellow": string;
    "blue": string;
    "magenta": string;
    "cyan": string;
    "white": string;
    "brightBlack": string;
    "brightRed": string;
    "brightGreen": string;
    "brightYellow": string;
    "brightBlue": string;
    "brightMagenta": string;
    "brightCyan": string;
    "brightWhite": string;

    /** Creates a new Palette instance. */
    constructor($$source: Partial<Palette> = {}) {
        if (!("black" in $$source)) {
            this["black"] = "";
        }
        if (!("red" in $$source)) {
            this["red"] = "";
        }
        if (!("green" in $$source)) {
            this["green"] = "";
        }
        if (!("yellow" in $$source)) {
            this["yellow"] = "";
        }
        if (!("blue" in $$source)) {
            this["blue"] = "";
        }
        if (!("magenta" in $$source)) {
            this["magenta"] = "";
        }
        if (!("cyan" in $$source)) {
            this["cyan"] = "";
        }
        if (!("white" in $$source)) {
            this["white"] = "";
        }
        if (!("brightBlack" in $$source)) {
            this["brightBlack"] = "";
        }
        if (!("brightRed" in $$source)) {
            this["brightRed"] = "";
        }
        if (!("brightGreen" in $$source)) {
            this["brightGreen"] = "";
        }
        if (!("brightYellow" in $$source)) {
            this["brightYellow"] = "";
        }
        if (!("brightBlue" in $$source)) {
            this["brightBlue"] = "";
        }
        if (!("brightMagenta" in $$source)) {
            this["brightMagenta"] = "";
        }
        if (!("brightCyan" in $$source)) {
            this["brightCyan"] = "";
        }
        if (!("brightWhite" in $$source)) {
            this["brightWhite"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Palette instance from a string or object.
     */
    static createFrom($$source: any = {}): Palette {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Palette($$parsedSource as Partial<Palette>);
    }
}

export class Settings {
    "themeId": string;
    "mode": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("themeId" in $$source)) {
            this["themeId"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

export class Theme {
    "id": string;
    "name": string;
    "dark": Palette;
    "light": Palette;

    /** Creates a new Theme instance. */
    constructor($$source: Partial<Theme> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dark" in $$source)) {
            this["dark"] = (new Palette());
        }
        if (!("light" in $$source)) {
            this["light"] = (new Palette());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Theme instance from a string or object.
     */
    static createFrom($$source: any = {}): Theme {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dark" in $$parsedSource) {
            $$parsedSource["dark"] = $$createField2_0($$parsedSource["dark"]);
        }
        if ("light" in $$parsedSource) {
            $$parsedSource["light"] = $$createField3_0($$parsedSource["light"]);
        }
        return new Theme($$parsedSource as Partial<Theme>);
    }
}

// Private type creation functions
const $$createType0 = Palette.createFrom;
