// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./store/models.js";

export function GetSettings(): $CancellablePromise<store$0.Settings> {
    return $Call.ByID(3034808949).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UpdateSettings(v: store$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(2846770304, v);
}

// Private type creation functions
const $$createType0 = store$0.Settings.createFrom;
