// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as shared$0 from "./shared/models.js";

export function Boot(): $CancellablePromise<void> {
    return $Call.ByID(380504861);
}

export function DeleteMessage(teamID: string, channelID: string, threadTs: string, ts: string): $CancellablePromise<void> {
    return $Call.ByID(3311734089, teamID, channelID, threadTs, ts);
}

export function DownloadFile(url: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(682707047, url, name);
}

export function GetAllCategories(teamID: string): $CancellablePromise<shared$0.Category[]> {
    return $Call.ByID(3050061730, teamID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetChannelInfo(teamID: string, channelID: string): $CancellablePromise<shared$0.Channel | null> {
    return $Call.ByID(1382314158, teamID, channelID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetChannels(teamID: string): $CancellablePromise<shared$0.Channel[]> {
    return $Call.ByID(3213025799, teamID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetIMByUserID(teamID: string, userID: string): $CancellablePromise<shared$0.Channel | null> {
    return $Call.ByID(1234218370, teamID, userID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetIMs(teamID: string): $CancellablePromise<shared$0.Channel[]> {
    return $Call.ByID(2667984826, teamID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetLatestMessages(teamID: string, channelID: string): $CancellablePromise<shared$0.MessagesResponse | null> {
    return $Call.ByID(872464680, teamID, channelID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetLatestThreadReplies(teamID: string, channelID: string, threadTS: string): $CancellablePromise<shared$0.MessagesResponse | null> {
    return $Call.ByID(3143471204, teamID, channelID, threadTS).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetMessagesAfter(teamID: string, channelID: string, after: string): $CancellablePromise<shared$0.MessagesResponse | null> {
    return $Call.ByID(1668011503, teamID, channelID, after).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetMessagesAround(teamID: string, channelID: string, anchor: string): $CancellablePromise<shared$0.MessagesResponse | null> {
    return $Call.ByID(3937011346, teamID, channelID, anchor).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetMessagesBefore(teamID: string, channelID: string, before: string): $CancellablePromise<shared$0.MessagesResponse | null> {
    return $Call.ByID(722489696, teamID, channelID, before).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetThreadRepliesAfter(teamID: string, channelID: string, threadTS: string, after: string): $CancellablePromise<shared$0.MessagesResponse | null> {
    return $Call.ByID(1373955833, teamID, channelID, threadTS, after).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetThreadRepliesBefore(teamID: string, channelID: string, threadTS: string, before: string): $CancellablePromise<shared$0.MessagesResponse | null> {
    return $Call.ByID(3750336238, teamID, channelID, threadTS, before).then(($result: any) => {
        return $$createType6($result);
    });
}

export function InvalidateEmojis(...names: string[]): $CancellablePromise<void> {
    return $Call.ByID(4123551535, names);
}

export function MarkAppReady(): $CancellablePromise<void> {
    return $Call.ByID(1753164810);
}

export function QuickUserChannelSearch(teamID: string, query: string): $CancellablePromise<shared$0.SearchResult[]> {
    return $Call.ByID(3793405766, teamID, query).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ResolveBots(teamID: string, appIDs: string[]): $CancellablePromise<{ [_ in string]?: shared$0.AppProfile }> {
    return $Call.ByID(3221068625, teamID, appIDs).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ResolveEmojis(teamID: string, names: string[]): $CancellablePromise<shared$0.Emoji[]> {
    return $Call.ByID(1381900964, teamID, names).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ResolveUsers(teamID: string, userIDs: string[]): $CancellablePromise<{ [_ in string]?: shared$0.UserProfile }> {
    return $Call.ByID(2167812529, teamID, userIDs).then(($result: any) => {
        return $$createType14($result);
    });
}

export function SendMessage(teamID: string, channelID: string, blocks: string, threadTS: string): $CancellablePromise<string> {
    return $Call.ByID(300632422, teamID, channelID, blocks, threadTS);
}

export function SendTyping(teamID: string, channelID: string, threadTS: string): $CancellablePromise<void> {
    return $Call.ByID(2103488488, teamID, channelID, threadTS);
}

// Private type creation functions
const $$createType0 = shared$0.Category.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = shared$0.Channel.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType2);
const $$createType5 = shared$0.MessagesResponse.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = shared$0.SearchResult.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = shared$0.AppProfile.createFrom;
const $$createType10 = $Create.Map($Create.Any, $$createType9);
const $$createType11 = shared$0.Emoji.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = shared$0.UserProfile.createFrom;
const $$createType14 = $Create.Map($Create.Any, $$createType13);
