// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as shared$0 from "./shared/models.js";

export function Boot(): $CancellablePromise<void> {
    return $Call.ByID(380504861);
}

export function DeleteMessage(teamID: string, channelID: string, threadTs: string, ts: string): $CancellablePromise<void> {
    return $Call.ByID(3311734089, teamID, channelID, threadTs, ts);
}

export function DownloadFile(url: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(682707047, url, name);
}

export function GetAllCategories(teamID: string): $CancellablePromise<shared$0.Category[]> {
    return $Call.ByID(3050061730, teamID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetChannelInfo(teamID: string, channelID: string): $CancellablePromise<shared$0.Channel | null> {
    return $Call.ByID(1382314158, teamID, channelID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetChannels(teamID: string): $CancellablePromise<shared$0.Channel[]> {
    return $Call.ByID(3213025799, teamID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetIMByUserID(teamID: string, userID: string): $CancellablePromise<shared$0.Channel | null> {
    return $Call.ByID(1234218370, teamID, userID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetIMs(teamID: string): $CancellablePromise<shared$0.Channel[]> {
    return $Call.ByID(2667984826, teamID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetMessages(teamID: string, channelID: string, cursor: string): $CancellablePromise<shared$0.MessagesResponse | null> {
    return $Call.ByID(1012973511, teamID, channelID, cursor).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetThreadMessages(teamID: string, channelID: string, threadTS: string, cursor: string): $CancellablePromise<shared$0.MessagesResponse | null> {
    return $Call.ByID(4013703191, teamID, channelID, threadTS, cursor).then(($result: any) => {
        return $$createType6($result);
    });
}

export function QuickUserChannelSearch(teamID: string, query: string): $CancellablePromise<shared$0.SearchResult[]> {
    return $Call.ByID(3793405766, teamID, query).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ResolveEmojis(teamID: string, names: string[]): $CancellablePromise<shared$0.Emoji[]> {
    return $Call.ByID(1381900964, teamID, names).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ResolveUsers(teamID: string, userIDs: string[]): $CancellablePromise<shared$0.UserProfile[]> {
    return $Call.ByID(2167812529, teamID, userIDs).then(($result: any) => {
        return $$createType12($result);
    });
}

export function SendMessage(teamID: string, channelID: string, blocks: string, threadTS: string): $CancellablePromise<string> {
    return $Call.ByID(300632422, teamID, channelID, blocks, threadTS);
}

export function SendTyping(teamID: string, channelID: string, threadTS: string): $CancellablePromise<void> {
    return $Call.ByID(2103488488, teamID, channelID, threadTS);
}

// Private type creation functions
const $$createType0 = shared$0.Category.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = shared$0.Channel.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType2);
const $$createType5 = shared$0.MessagesResponse.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = shared$0.SearchResult.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = shared$0.Emoji.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = shared$0.UserProfile.createFrom;
const $$createType12 = $Create.Array($$createType11);
