// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./store/models.js";

export function GetTheme(id: string): $CancellablePromise<store$0.Theme> {
    return $Call.ByID(3482301073, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListInvalidThemes(): $CancellablePromise<store$0.InvalidTheme[]> {
    return $Call.ByID(570967077).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListThemes(): $CancellablePromise<store$0.Theme[]> {
    return $Call.ByID(2467410722).then(($result: any) => {
        return $$createType3($result);
    });
}

export function OpenThemesDir(): $CancellablePromise<void> {
    return $Call.ByID(665197321);
}

export function ReloadThemes(): $CancellablePromise<void> {
    return $Call.ByID(3886765291);
}

// Private type creation functions
const $$createType0 = store$0.Theme.createFrom;
const $$createType1 = store$0.InvalidTheme.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
