// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../encoding/json/models.js";

export class AppAuth {
    "created_by": string;
    "date_created": string;
    "scopes": string[];
    "username": string;
    "full_name": string;
    "real_name": string;
    "icons": AppIcons;

    /** Creates a new AppAuth instance. */
    constructor($$source: Partial<AppAuth> = {}) {
        if (!("created_by" in $$source)) {
            this["created_by"] = "";
        }
        if (!("date_created" in $$source)) {
            this["date_created"] = "";
        }
        if (!("scopes" in $$source)) {
            this["scopes"] = [];
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("full_name" in $$source)) {
            this["full_name"] = "";
        }
        if (!("real_name" in $$source)) {
            this["real_name"] = "";
        }
        if (!("icons" in $$source)) {
            this["icons"] = (new AppIcons());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppAuth instance from a string or object.
     */
    static createFrom($$source: any = {}): AppAuth {
        const $$createField2_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scopes" in $$parsedSource) {
            $$parsedSource["scopes"] = $$createField2_0($$parsedSource["scopes"]);
        }
        if ("icons" in $$parsedSource) {
            $$parsedSource["icons"] = $$createField6_0($$parsedSource["icons"]);
        }
        return new AppAuth($$parsedSource as Partial<AppAuth>);
    }
}

export class AppBotUser {
    "id": string;
    "username": string;
    "memberships_count": number;

    /** Creates a new AppBotUser instance. */
    constructor($$source: Partial<AppBotUser> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("memberships_count" in $$source)) {
            this["memberships_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppBotUser instance from a string or object.
     */
    static createFrom($$source: any = {}): AppBotUser {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppBotUser($$parsedSource as Partial<AppBotUser>);
    }
}

export class AppCommand {
    "usage": string;
    "desc": string;
    "name": string;
    "type": string;
    "app": string;

    /** Creates a new AppCommand instance. */
    constructor($$source: Partial<AppCommand> = {}) {
        if (!("usage" in $$source)) {
            this["usage"] = "";
        }
        if (!("desc" in $$source)) {
            this["desc"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("app" in $$source)) {
            this["app"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppCommand instance from a string or object.
     */
    static createFrom($$source: any = {}): AppCommand {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppCommand($$parsedSource as Partial<AppCommand>);
    }
}

export class AppIcons {
    "emoji"?: string;
    "image_original"?: string;
    "image_24"?: string;
    "image_32"?: string;
    "image_36"?: string;
    "image_48"?: string;
    "image_64"?: string;
    "image_72"?: string;
    "image_96"?: string;
    "image_128"?: string;
    "image_192"?: string;
    "image_512"?: string;
    "image_1024"?: string;

    /** Creates a new AppIcons instance. */
    constructor($$source: Partial<AppIcons> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppIcons instance from a string or object.
     */
    static createFrom($$source: any = {}): AppIcons {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppIcons($$parsedSource as Partial<AppIcons>);
    }
}

export class AppProfile {
    "id": string;
    "name": string;
    "developer_name": string;
    "desc": string;
    "long_desc": string;
    "long_desc_formatted": string;
    "url": string;
    "support_url": string;
    "config_url": string;
    "app_card_color": string;
    "installation_summary": string;
    "team_id": string;
    "enterprise_id": string;
    "is_certified": boolean;
    "is_directory_published": boolean;
    "is_distributed": boolean;
    "is_ai_app": boolean;
    "is_agent_app": boolean;
    "is_workflow_app": boolean;
    "date_installed": number;
    "commands": { [_ in string]?: AppCommand };
    "categories": { [_ in string]?: json$0.RawMessage };
    "screenshots": AppScreenshot[];
    "icons": AppIcons;
    "bot_user": AppBotUser;
    "auth": AppAuth;
    "security_compliance"?: json$0.RawMessage;

    /** Creates a new AppProfile instance. */
    constructor($$source: Partial<AppProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("developer_name" in $$source)) {
            this["developer_name"] = "";
        }
        if (!("desc" in $$source)) {
            this["desc"] = "";
        }
        if (!("long_desc" in $$source)) {
            this["long_desc"] = "";
        }
        if (!("long_desc_formatted" in $$source)) {
            this["long_desc_formatted"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("support_url" in $$source)) {
            this["support_url"] = "";
        }
        if (!("config_url" in $$source)) {
            this["config_url"] = "";
        }
        if (!("app_card_color" in $$source)) {
            this["app_card_color"] = "";
        }
        if (!("installation_summary" in $$source)) {
            this["installation_summary"] = "";
        }
        if (!("team_id" in $$source)) {
            this["team_id"] = "";
        }
        if (!("enterprise_id" in $$source)) {
            this["enterprise_id"] = "";
        }
        if (!("is_certified" in $$source)) {
            this["is_certified"] = false;
        }
        if (!("is_directory_published" in $$source)) {
            this["is_directory_published"] = false;
        }
        if (!("is_distributed" in $$source)) {
            this["is_distributed"] = false;
        }
        if (!("is_ai_app" in $$source)) {
            this["is_ai_app"] = false;
        }
        if (!("is_agent_app" in $$source)) {
            this["is_agent_app"] = false;
        }
        if (!("is_workflow_app" in $$source)) {
            this["is_workflow_app"] = false;
        }
        if (!("date_installed" in $$source)) {
            this["date_installed"] = 0;
        }
        if (!("commands" in $$source)) {
            this["commands"] = {};
        }
        if (!("categories" in $$source)) {
            this["categories"] = {};
        }
        if (!("screenshots" in $$source)) {
            this["screenshots"] = [];
        }
        if (!("icons" in $$source)) {
            this["icons"] = (new AppIcons());
        }
        if (!("bot_user" in $$source)) {
            this["bot_user"] = (new AppBotUser());
        }
        if (!("auth" in $$source)) {
            this["auth"] = (new AppAuth());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): AppProfile {
        const $$createField20_0 = $$createType3;
        const $$createField21_0 = $$createType4;
        const $$createField22_0 = $$createType6;
        const $$createField23_0 = $$createType1;
        const $$createField24_0 = $$createType7;
        const $$createField25_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField20_0($$parsedSource["commands"]);
        }
        if ("categories" in $$parsedSource) {
            $$parsedSource["categories"] = $$createField21_0($$parsedSource["categories"]);
        }
        if ("screenshots" in $$parsedSource) {
            $$parsedSource["screenshots"] = $$createField22_0($$parsedSource["screenshots"]);
        }
        if ("icons" in $$parsedSource) {
            $$parsedSource["icons"] = $$createField23_0($$parsedSource["icons"]);
        }
        if ("bot_user" in $$parsedSource) {
            $$parsedSource["bot_user"] = $$createField24_0($$parsedSource["bot_user"]);
        }
        if ("auth" in $$parsedSource) {
            $$parsedSource["auth"] = $$createField25_0($$parsedSource["auth"]);
        }
        return new AppProfile($$parsedSource as Partial<AppProfile>);
    }
}

export class AppScreenshot {
    "id": string;
    "image_440"?: string;
    "image_1000"?: string;
    "image_1600"?: string;
    "image_original"?: string;

    /** Creates a new AppScreenshot instance. */
    constructor($$source: Partial<AppScreenshot> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppScreenshot instance from a string or object.
     */
    static createFrom($$source: any = {}): AppScreenshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppScreenshot($$parsedSource as Partial<AppScreenshot>);
    }
}

export class Category {
    "channel_section_id": string;
    "name": string;
    "type": string;
    "emoji"?: string;
    "next_channel_section_id"?: string;
    "last_updated"?: number;
    "is_redacted"?: boolean;
    "channel_ids_page": {"channel_ids": string[], "count": number, "cursor"?: string};

    /** Creates a new Category instance. */
    constructor($$source: Partial<Category> = {}) {
        if (!("channel_section_id" in $$source)) {
            this["channel_section_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("channel_ids_page" in $$source)) {
            this["channel_ids_page"] = {"channel_ids": [], "count": 0};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Category instance from a string or object.
     */
    static createFrom($$source: any = {}): Category {
        const $$createField7_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channel_ids_page" in $$parsedSource) {
            $$parsedSource["channel_ids_page"] = $$createField7_0($$parsedSource["channel_ids_page"]);
        }
        return new Category($$parsedSource as Partial<Category>);
    }
}

export class Channel {
    "id": string;
    "name"?: string;
    "is_channel": boolean;
    "is_group": boolean;
    "is_im": boolean;
    "is_mpim": boolean;
    "is_private": boolean;
    "created": number;
    "is_archived": boolean;
    "updated": number;
    "creator"?: string;

    /**
     * userBoot fields
     */
    "is_general"?: boolean;
    "name_normalized"?: string;
    "is_shared"?: boolean;
    "is_frozen"?: boolean;
    "is_org_shared"?: boolean;
    "is_ext_shared"?: boolean;
    "context_team_id"?: string;
    "shared_team_ids"?: string[];
    "internal_team_ids"?: string[];
    "members"?: string[];

    /**
     * conversations.info / IM fields
     */
    "user"?: string;
    "is_open"?: boolean;
    "last_read"?: string;
    "priority"?: number;
    "unread_count"?: number;
    "unread_count_display"?: number;
    "latest"?: Message | null;
    "topic": {"value": string, "creator": string, "last_set": number};
    "purpose": {"value": string, "creator": string, "last_set": number};
    "properties": {"tabs"?: Tab[], "posting_restricted_to"?: {"type": string[], "user": string[]} | null, "is_dormant"?: boolean, "canvas"?: {"file_id": string, "is_empty": boolean, "quip_thread_id": string} | null};
    "previous_names"?: string[];

    /** Creates a new Channel instance. */
    constructor($$source: Partial<Channel> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("is_channel" in $$source)) {
            this["is_channel"] = false;
        }
        if (!("is_group" in $$source)) {
            this["is_group"] = false;
        }
        if (!("is_im" in $$source)) {
            this["is_im"] = false;
        }
        if (!("is_mpim" in $$source)) {
            this["is_mpim"] = false;
        }
        if (!("is_private" in $$source)) {
            this["is_private"] = false;
        }
        if (!("created" in $$source)) {
            this["created"] = 0;
        }
        if (!("is_archived" in $$source)) {
            this["is_archived"] = false;
        }
        if (!("updated" in $$source)) {
            this["updated"] = 0;
        }
        if (!("topic" in $$source)) {
            this["topic"] = {"value": "", "creator": "", "last_set": 0};
        }
        if (!("purpose" in $$source)) {
            this["purpose"] = {"value": "", "creator": "", "last_set": 0};
        }
        if (!("properties" in $$source)) {
            this["properties"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Channel instance from a string or object.
     */
    static createFrom($$source: any = {}): Channel {
        const $$createField18_0 = $$createType0;
        const $$createField19_0 = $$createType0;
        const $$createField20_0 = $$createType0;
        const $$createField27_0 = $$createType11;
        const $$createField30_0 = $$createType16;
        const $$createField31_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shared_team_ids" in $$parsedSource) {
            $$parsedSource["shared_team_ids"] = $$createField18_0($$parsedSource["shared_team_ids"]);
        }
        if ("internal_team_ids" in $$parsedSource) {
            $$parsedSource["internal_team_ids"] = $$createField19_0($$parsedSource["internal_team_ids"]);
        }
        if ("members" in $$parsedSource) {
            $$parsedSource["members"] = $$createField20_0($$parsedSource["members"]);
        }
        if ("latest" in $$parsedSource) {
            $$parsedSource["latest"] = $$createField27_0($$parsedSource["latest"]);
        }
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField30_0($$parsedSource["properties"]);
        }
        if ("previous_names" in $$parsedSource) {
            $$parsedSource["previous_names"] = $$createField31_0($$parsedSource["previous_names"]);
        }
        return new Channel($$parsedSource as Partial<Channel>);
    }
}

export class Emoji {
    "name": string;
    "value": string;
    "unicode"?: string;
    "updated": number;

    /** Creates a new Emoji instance. */
    constructor($$source: Partial<Emoji> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("updated" in $$source)) {
            this["updated"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Emoji instance from a string or object.
     */
    static createFrom($$source: any = {}): Emoji {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Emoji($$parsedSource as Partial<Emoji>);
    }
}

export class File {
    "id": string;
    "created": number;
    "timestamp": json$0.Number;
    "mimetype": string;
    "filetype": string;
    "pretty_type": string;
    "user": string;
    "user_team": string;
    "editable": boolean;
    "size": number;
    "mode": string;
    "is_external": boolean;
    "external_type": string;
    "is_public": boolean;
    "public_url_shared": boolean;
    "display_as_bot": boolean;
    "username"?: string;
    "name"?: string;
    "title"?: string;
    "url_private"?: string;
    "url_private_download"?: string;
    "media_display_type"?: string;

    /**
     * very smol
     */
    "thumb_64"?: string;
    "thumb_80"?: string;
    "thumb_160"?: string;
    "thumb_360"?: string;
    "thumb_360_w"?: number;
    "thumb_360_h"?: number;
    "thumb_480"?: string;
    "thumb_480_w"?: number;
    "thumb_480_h"?: number;
    "thumb_720"?: string;
    "thumb_720_w"?: number;
    "thumb_720_h"?: number;
    "thumb_800"?: string;
    "thumb_800_w"?: number;
    "thumb_800_h"?: number;
    "thumb_960"?: string;
    "thumb_960_w"?: number;
    "thumb_960_h"?: number;
    "thumb_1024"?: string;
    "thumb_1024_w"?: number;
    "thumb_1024_h"?: number;
    "thumb_tiny"?: string;
    "thumb_pdf"?: string;
    "thumb_video"?: string;
    "thumb_360_gif"?: string;
    "original_w"?: number;
    "original_h"?: number;
    "permalink"?: string;
    "permalink_public"?: string;
    "has_rich_preview"?: boolean;
    "is_starred"?: boolean;
    "file_access"?: string;

    /** Creates a new File instance. */
    constructor($$source: Partial<File> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = 0;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }
        if (!("mimetype" in $$source)) {
            this["mimetype"] = "";
        }
        if (!("filetype" in $$source)) {
            this["filetype"] = "";
        }
        if (!("pretty_type" in $$source)) {
            this["pretty_type"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("user_team" in $$source)) {
            this["user_team"] = "";
        }
        if (!("editable" in $$source)) {
            this["editable"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("is_external" in $$source)) {
            this["is_external"] = false;
        }
        if (!("external_type" in $$source)) {
            this["external_type"] = "";
        }
        if (!("is_public" in $$source)) {
            this["is_public"] = false;
        }
        if (!("public_url_shared" in $$source)) {
            this["public_url_shared"] = false;
        }
        if (!("display_as_bot" in $$source)) {
            this["display_as_bot"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new File instance from a string or object.
     */
    static createFrom($$source: any = {}): File {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new File($$parsedSource as Partial<File>);
    }
}

export class Message {
    "user": string;
    "text": string;
    "ts": string;
    "type": string;
    "subtype"?: string;
    "team"?: string;
    "thread_ts"?: string;
    "reply_count"?: number;
    "latest_reply"?: string;
    "reply_users"?: string[];
    "blocks"?: json$0.RawMessage;
    "edited"?: json$0.RawMessage;
    "bot_profile"?: json$0.RawMessage;
    "files"?: File[];
    "bot_id"?: string;
    "app_id"?: string;
    "username"?: string;
    "icons"?: AppIcons | null;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("ts" in $$source)) {
            this["ts"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField9_0 = $$createType0;
        const $$createField13_0 = $$createType18;
        const $$createField17_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reply_users" in $$parsedSource) {
            $$parsedSource["reply_users"] = $$createField9_0($$parsedSource["reply_users"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField13_0($$parsedSource["files"]);
        }
        if ("icons" in $$parsedSource) {
            $$parsedSource["icons"] = $$createField17_0($$parsedSource["icons"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

export class MessagesResponse {
    "messages": Message[];
    "has_more": boolean;
    "oldest_ts"?: string;
    "latest_ts"?: string;

    /** Creates a new MessagesResponse instance. */
    constructor($$source: Partial<MessagesResponse> = {}) {
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("has_more" in $$source)) {
            this["has_more"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessagesResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): MessagesResponse {
        const $$createField0_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField0_0($$parsedSource["messages"]);
        }
        return new MessagesResponse($$parsedSource as Partial<MessagesResponse>);
    }
}

export class SearchResult {
    "ChannelID": string;
    "Name": string;
    "Type": string;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("ChannelID" in $$source)) {
            this["ChannelID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

export class SlackSession {
    "d_cookie": string;
    "workspaces": { [_ in string]?: WorkspaceSession };

    /** Creates a new SlackSession instance. */
    constructor($$source: Partial<SlackSession> = {}) {
        if (!("d_cookie" in $$source)) {
            this["d_cookie"] = "";
        }
        if (!("workspaces" in $$source)) {
            this["workspaces"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SlackSession instance from a string or object.
     */
    static createFrom($$source: any = {}): SlackSession {
        const $$createField1_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workspaces" in $$parsedSource) {
            $$parsedSource["workspaces"] = $$createField1_0($$parsedSource["workspaces"]);
        }
        return new SlackSession($$parsedSource as Partial<SlackSession>);
    }
}

export class Tab {
    "type": string;
    "label"?: string;
    "id"?: string;
    "is_disabled"?: boolean | null;
    "data"?: {"file_id"?: string, "shared_ts"?: string, "mute_edit_updates"?: boolean, "folder_bookmark_id"?: string} | null;

    /** Creates a new Tab instance. */
    constructor($$source: Partial<Tab> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tab instance from a string or object.
     */
    static createFrom($$source: any = {}): Tab {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tab($$parsedSource as Partial<Tab>);
    }
}

export class UserProfile {
    "id": string;
    "color": string;
    "is_bot": boolean;
    "tz": string;
    "tz_label": string;
    "tz_offset": number;
    "profile": {"display_name": string, "real_name": string, "avatar_hash": string, "title": string, "phone": string, "status_text": string, "status_emoji": string, "first_name": string, "last_name": string};

    /** Creates a new UserProfile instance. */
    constructor($$source: Partial<UserProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("is_bot" in $$source)) {
            this["is_bot"] = false;
        }
        if (!("tz" in $$source)) {
            this["tz"] = "";
        }
        if (!("tz_label" in $$source)) {
            this["tz_label"] = "";
        }
        if (!("tz_offset" in $$source)) {
            this["tz_offset"] = 0;
        }
        if (!("profile" in $$source)) {
            this["profile"] = {"display_name": "", "real_name": "", "avatar_hash": "", "title": "", "phone": "", "status_text": "", "status_emoji": "", "first_name": "", "last_name": ""};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): UserProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserProfile($$parsedSource as Partial<UserProfile>);
    }
}

export class WorkspaceSession {
    "token": string;
    "user_id": string;
    "team_name": string;
    "team_url": string;
    "team_icon": string;
    "enterprise_id"?: string;

    /** Creates a new WorkspaceSession instance. */
    constructor($$source: Partial<WorkspaceSession> = {}) {
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("user_id" in $$source)) {
            this["user_id"] = "";
        }
        if (!("team_name" in $$source)) {
            this["team_name"] = "";
        }
        if (!("team_url" in $$source)) {
            this["team_url"] = "";
        }
        if (!("team_icon" in $$source)) {
            this["team_icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceSession instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceSession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceSession($$parsedSource as Partial<WorkspaceSession>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = AppIcons.createFrom;
const $$createType2 = AppCommand.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = AppScreenshot.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = AppBotUser.createFrom;
const $$createType8 = AppAuth.createFrom;
const $$createType9 = $Create.Struct({
    "channel_ids": $$createType0,
});
const $$createType10 = Message.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = Tab.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Struct({
    "type": $$createType0,
    "user": $$createType0,
});
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Struct({
    "tabs": $$createType13,
    "posting_restricted_to": $$createType15,
});
const $$createType17 = File.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Nullable($$createType1);
const $$createType20 = $Create.Array($$createType10);
const $$createType21 = WorkspaceSession.createFrom;
const $$createType22 = $Create.Map($Create.Any, $$createType21);
